<a href="https://colab.research.google.com/github/melchizedek79/3-1/blob/main/IRS/EXP_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from sklearn.datasets import fetch_20newsgroups
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans
from sklearn.metrics import confusion_matrix
import numpy as np

# Categories
categories = [
    'comp.graphics',
    'rec.sport.baseball',
    'sci.space'
]

# Load the 20 Newsgroups dataset
newsgroups = fetch_20newsgroups(
    subset='all',
    categories=categories,
    remove=('headers', 'footers', 'quotes')
)

documents = newsgroups.data
true_labels = newsgroups.target

# Number of clusters
num_clusters = len(categories)

print(f"Total documents: {len(documents)}")
print(f"Categories: {categories}")

# TF-IDF Vectorization
vectorizer = TfidfVectorizer(
    stop_words='english',
    max_df=0.5
)

X = vectorizer.fit_transform(documents)

# K-Means Clustering
kmeans = KMeans(
    n_clusters=num_clusters,
    random_state=42,
    n_init=10
)

kmeans.fit(X)

cluster_labels = kmeans.labels_

# Confusion Matrix
cm = confusion_matrix(true_labels, cluster_labels)

print("\nConfusion Matrix:")
print(cm)

# Evaluation Metrics
precision_list = []
recall_list = []
fmeasure_list = []

for i in range(num_clusters):
    true_cluster = cm[:, i]
    predicted_cluster = cm[i, :]

    tp = np.max(true_cluster)
    fp = np.sum(true_cluster) - tp
    fn = np.sum(predicted_cluster) - tp

    precision = tp / (tp + fp + 1e-10)
    recall = tp / (tp + fn + 1e-10)
    fmeasure = (2 * precision * recall) / (
        precision + recall + 1e-10
    )

    precision_list.append(precision)
    recall_list.append(recall)
    fmeasure_list.append(fmeasure)

# Average Metrics
avg_precision = np.mean(precision_list)
avg_recall = np.mean(recall_list)
avg_fmeasure = np.mean(fmeasure_list)

# Display Results
print("\n=== Evaluation Metrics ===")
print(f"Precision:  {avg_precision:.4f}")
print(f"Recall:     {avg_recall:.4f}")
print(f"F-Measure:  {avg_fmeasure:.4f}")

print("\nConfusion Matrix:")
print(cm)

Total documents: 2954
Categories: ['comp.graphics', 'rec.sport.baseball', 'sci.space']

Confusion Matrix:
[[  1 389 583]
 [532 431  31]
 [  1 950  36]]

=== Evaluation Metrics ===
Precision:  0.8100
Recall:     0.6977
F-Measure:  0.7019

Confusion Matrix:
[[  1 389 583]
 [532 431  31]
 [  1 950  36]]
